Repository googleapis/python-websecurityscanner, pull requests merged in 2021-04, with the labels that each got.

#45 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#46 chore: add constraints file check for python samples
  .github/header-checker-lint.yml
  renovate.json
  synth.metadata
Labels: api: websecurityscanner, cla: yes, context: full, samples

#48 chore: prevent normalization of semver versioning
  setup.py
Labels: api: websecurityscanner, cla: yes

#47 chore: update templates
  .kokoro/release.sh
  .kokoro/release/common.cfg
  docs/_static/custom.css
  synth.metadata
Labels: api: websecurityscanner, automerge, cla: yes, context: full

#49 chore(revert): revert preventing normalization
  setup.py
Labels: api: websecurityscanner, cla: yes
